/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author ASUS ROG G14
 */
public class Menu extends javax.swing.JFrame {
    int idUsuarioSesion;
    int idRolSesion;
    String nombreSesion;
    /**
     * Creates new form Menu
     */
    public Menu(int idUser, int idRol, String username) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.idUsuarioSesion = idUser;
        this.idRolSesion = idRol;
        this.nombreSesion = username;
        
        if (this.idRolSesion == 2) {
            jBtnProductos.setEnabled(false); 
            jBtnUsuarios.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnVentas = new javax.swing.JButton();
        jBtnProductos = new javax.swing.JButton();
        jBtnUsuarios = new javax.swing.JButton();
        jBtnClientes = new javax.swing.JButton();
        jBtnReporteVentas = new javax.swing.JButton();
        jBtnReporteMasVendido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnVentas.setText("Ventas");
        jBtnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVentasActionPerformed(evt);
            }
        });

        jBtnProductos.setText("Productos");
        jBtnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProductosActionPerformed(evt);
            }
        });

        jBtnUsuarios.setText("Usuarios");
        jBtnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUsuariosActionPerformed(evt);
            }
        });

        jBtnClientes.setText("Clientes");
        jBtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClientesActionPerformed(evt);
            }
        });

        jBtnReporteVentas.setText("Reporte de Ventas");
        jBtnReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReporteVentasActionPerformed(evt);
            }
        });

        jBtnReporteMasVendido.setText("Reporte Más Vendido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jBtnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnReporteVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jBtnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnReporteMasVendido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jBtnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(jBtnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnReporteVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(jBtnReporteMasVendido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClientesActionPerformed
        // TODO add your handling code here:
        Clientes ventanaClientes = new Clientes();

        ventanaClientes.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        ventanaClientes.setLocationRelativeTo(null);
        ventanaClientes.setVisible(true);
    }//GEN-LAST:event_jBtnClientesActionPerformed

    private void jBtnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVentasActionPerformed
        // TODO add your handling code here:
        Ventas ventanaVentas = new Ventas(this.idUsuarioSesion);
        ventanaVentas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnVentasActionPerformed

    private void jBtnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProductosActionPerformed
        // TODO add your handling code here:
        Productos ventanaProductos = new Productos();
        ventanaProductos.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        ventanaProductos.setLocationRelativeTo(null);
        ventanaProductos.setVisible(true);
    }//GEN-LAST:event_jBtnProductosActionPerformed

    private void jBtnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUsuariosActionPerformed
        // TODO add your handling code here:
        Usuarios ventanaUsuarios = new Usuarios();

        ventanaUsuarios.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        ventanaUsuarios.setLocationRelativeTo(null);
        ventanaUsuarios.setVisible(true);
    }//GEN-LAST:event_jBtnUsuariosActionPerformed

    private void jBtnReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReporteVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnReporteVentasActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClientes;
    private javax.swing.JButton jBtnProductos;
    private javax.swing.JButton jBtnReporteMasVendido;
    private javax.swing.JButton jBtnReporteVentas;
    private javax.swing.JButton jBtnUsuarios;
    private javax.swing.JButton jBtnVentas;
    // End of variables declaration//GEN-END:variables
}
