/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import modelo.Conexion;


/**
 *
 * @author ASUS ROG G14
 */
public class Productos extends javax.swing.JFrame {
    dao.ProductoDAO prodDao = new dao.ProductoDAO();
    modelo.Producto producto = new modelo.Producto();
    javax.swing.table.DefaultTableModel modeloTabla;
    DefaultTableModel tablita = new DefaultTableModel();
    String codigoSeleccionado = "";
    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        cargartabla();
        listarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtCode = new javax.swing.JTextField();
        jTxtName = new javax.swing.JTextField();
        jTxtPrecio = new javax.swing.JTextField();
        jTxtStock = new javax.swing.JTextField();
        jBtnGuardar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblCrud = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código del Producto");

        jLabel2.setText("Nombre del Producto");

        jLabel3.setText("Precio del Producto");

        jLabel4.setText("Stock del Producto");

        jLabel5.setText("Ingreso de Productos");

        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBtnEditar.setText("Editar");
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jTblCrud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblCrud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblCrudMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblCrud);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtCode, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtName)
                                    .addComponent(jTxtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jTxtStock))))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jBtnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEliminar))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        // TODO add your handling code here:
        if (!"".equals(jTxtCode.getText()) && !"".equals(jTxtName.getText()) && 
            !"".equals(jTxtPrecio.getText()) && !"".equals(jTxtStock.getText())) {

            producto.setCodigo(jTxtCode.getText());
            producto.setNombre(jTxtName.getText());
            producto.setPrecio(Double.parseDouble(jTxtPrecio.getText()));
            producto.setStock(Integer.parseInt(jTxtStock.getText()));

            if (prodDao.insertar(producto)) {
                javax.swing.JOptionPane.showMessageDialog(null, "Producto Guardado");
                limpiarCampos();
                listarProductos();
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Por favor, llena todos los campos");
        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jTblCrudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblCrudMouseClicked
        // TODO add your handling code here:
        int fila = jTblCrud.rowAtPoint(evt.getPoint());
        if (fila > -1) {
            // Guardamos el código original en nuestra variable global
            codigoSeleccionado = jTblCrud.getValueAt(fila, 0).toString();

            // Pasamos los datos a las cajitas de texto
            jTxtCode.setText(codigoSeleccionado);
            jTxtName.setText(jTblCrud.getValueAt(fila, 1).toString());
            jTxtPrecio.setText(jTblCrud.getValueAt(fila, 2).toString());
            jTxtStock.setText(jTblCrud.getValueAt(fila, 3).toString());
        }
    }//GEN-LAST:event_jTblCrudMouseClicked

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        // TODO add your handling code here:
        if (codigoSeleccionado.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Selecciona una fila en la tabla primero");
        } else {
            producto.setCodigo(jTxtCode.getText());
            producto.setNombre(jTxtName.getText());
            producto.setPrecio(Double.parseDouble(jTxtPrecio.getText()));
            producto.setStock(Integer.parseInt(jTxtStock.getText()));

            if (prodDao.actualizarPorCodigo(producto, codigoSeleccionado)) {
                javax.swing.JOptionPane.showMessageDialog(null, "Producto Actualizado");
                limpiarCampos();
                listarProductos();
                codigoSeleccionado = "";
            }
        }
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        // TODO add your handling code here:
        if (codigoSeleccionado.equals("")) {
                javax.swing.JOptionPane.showMessageDialog(null, "Selecciona una fila en la tabla primero");
            } else {
                int pregunta = javax.swing.JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar este producto?");
                if (pregunta == 0) { 
                    if (prodDao.eliminarPorCodigo(codigoSeleccionado)) {
                        javax.swing.JOptionPane.showMessageDialog(null, "Producto Eliminado");
                        limpiarCampos(); 
                        listarProductos(); 
                        codigoSeleccionado = ""; 
                    }
                }
            }
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }
    
    public void cargartabla(){
        jTblCrud.setModel(tablita);
        tablita.addColumn("Código");
        tablita.addColumn("Nombre");
        tablita.addColumn("Precio");
        tablita.addColumn("Stock");
    
    }
    
    public void listarProductos() {
        try {
            tablita.setRowCount(0);
            Connection con = Conexion.conectar();
            
            String sql = "SELECT * FROM productos";
            String Fila[] = new String[4];
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()){
                Fila[0] = rs.getString("codigo");
                Fila[1] = rs.getString("nombre");
                Fila[2] = rs.getString("precio");
                Fila[3] = rs.getString("stock");
                
                tablita.addRow(Fila);
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo cargar los productos");
        }

    }

    public void limpiarCampos() {
        jTxtCode.setText("");
        jTxtName.setText("");
        jTxtPrecio.setText("");
        jTxtStock.setText("");
        codigoSeleccionado = "";
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblCrud;
    private javax.swing.JTextField jTxtCode;
    private javax.swing.JTextField jTxtName;
    private javax.swing.JTextField jTxtPrecio;
    private javax.swing.JTextField jTxtStock;
    // End of variables declaration//GEN-END:variables
}
