/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Conexion;
import java.sql.*;

/**
 *
 * @author ASUS ROG G14
 */
public class Usuarios extends javax.swing.JFrame {
    dao.UsuarioDAO usrDao = new dao.UsuarioDAO();
    modelo.Usuario usuario = new modelo.Usuario();
    DefaultComboBoxModel combito = new DefaultComboBoxModel();
    DefaultTableModel tablitaUsuarios = new DefaultTableModel();
    String userSeleccionado = "";
    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        cargartabla();
        listarUsuarios();
        cargarRoles();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPsfContra = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jTxtUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCbxRol = new javax.swing.JComboBox<>();
        jBtnGuardar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingreso de Usuarios");

        jLabel2.setText("Nombre");

        jLabel3.setText("Contraseña");

        jLabel4.setText("Rol");

        jCbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBtnEditar.setText("Editar");
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jTblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)
                        .addGap(0, 142, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCbxRol, 0, 116, Short.MAX_VALUE)
                            .addComponent(jPsfContra)
                            .addComponent(jTxtUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPsfContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jBtnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnEliminar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        // TODO add your handling code here:
        if (!"".equals(jTxtUser.getText()) && jPsfContra.getPassword().length > 0) {

            usuario.setUsername(jTxtUser.getText());
            usuario.setPassword(new String(jPsfContra.getPassword()));
            usuario.setIdRol(jCbxRol.getSelectedIndex() + 1); 
            usuario.setActivo(true);

            if (usrDao.insertar(usuario)) {
                javax.swing.JOptionPane.showMessageDialog(null, "Usuario Guardado exitosamente");
                limpiarCampos();
                listarUsuarios();
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Por favor, llena todos los campos");
        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jTblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblUsuariosMouseClicked
        // TODO add your handling code here:
        int fila = jTblUsuarios.rowAtPoint(evt.getPoint());

            if (fila > -1) {
                Object valorCelda = jTblUsuarios.getValueAt(fila, 0);

                if (valorCelda != null) {
                    userSeleccionado = valorCelda.toString();

                    jTxtUser.setText(userSeleccionado);
                    jPsfContra.setText(""); 

                    Object valorRol = jTblUsuarios.getValueAt(fila, 2);
                    if (valorRol != null) {
                        jCbxRol.setSelectedItem(valorRol.toString());
                    }
                }
            }
    }//GEN-LAST:event_jTblUsuariosMouseClicked

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        // TODO add your handling code here:
        if (userSeleccionado.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Selecciona una fila en la tabla primero");
        } else {
            usuario.setUsername(jTxtUser.getText());
            usuario.setPassword(new String(jPsfContra.getPassword()));
            usuario.setIdRol(jCbxRol.getSelectedIndex() + 1);
            usuario.setActivo(true);

            if (usrDao.actualizarPorUsername(usuario, userSeleccionado)) {
                javax.swing.JOptionPane.showMessageDialog(null, "Usuario Actualizado exitosamente");
                limpiarCampos();
                listarUsuarios();
                userSeleccionado = "";
            }
    }
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        // TODO add your handling code here:
        if (userSeleccionado.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Selecciona una fila en la tabla primero");
        } else {
            int pregunta = javax.swing.JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar a este usuario?");
            if (pregunta == 0) { 
                if (usrDao.eliminarPorUsername(userSeleccionado)) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Usuario Eliminado");
                    limpiarCampos();
                    listarUsuarios();
                    userSeleccionado = "";
                }
            }
        }
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }
    
    public void cargarRoles() {
        jCbxRol.setModel(combito);
        jCbxRol.removeAllItems(); 
        java.util.List<String> roles = usrDao.consultarRoles();
        for (String rol : roles) {
            jCbxRol.addItem(rol);
        }
    }

    public void listarUsuarios() {
        try {
            tablitaUsuarios.setRowCount(0); 
            Connection con = Conexion.conectar();
            String sql = "SELECT u.username, u.password_hash, r.nombre AS nombre_rol " + "FROM usuarios u INNER JOIN roles r ON u.id_rol = r.id_rol";

            String Fila[] = new String[3];

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Fila[0] = rs.getString("username");
                Fila[1] = "********";
                Fila[2] = rs.getString("nombre_rol"); 

                tablitaUsuarios.addRow(Fila);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo cargar los usuarios: " + ex.getMessage());
        }
    }
    public void cargartabla() {
        jTblUsuarios.setModel(tablitaUsuarios);
        tablitaUsuarios.addColumn("Usuario");
        tablitaUsuarios.addColumn("Contraseña");
        tablitaUsuarios.addColumn("Rol");
    }

    public void limpiarCampos() {
        jTxtUser.setText("");
        jPsfContra.setText("");
        if(jCbxRol.getItemCount() > 0) {
            jCbxRol.setSelectedIndex(0);
        }
        userSeleccionado = "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JComboBox<String> jCbxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPsfContra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblUsuarios;
    private javax.swing.JTextField jTxtUser;
    // End of variables declaration//GEN-END:variables
}
