/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS ROG G14
 */
public class Ventas extends javax.swing.JFrame {
    int idCajeroActivo;
    DefaultTableModel tablita = new DefaultTableModel();
    double subtotalVenta = 0.0;
    double ivaVenta = 0.0;
    double totalVenta = 0.0;
    int idClienteFactura = 0;
    modelo.Producto productoTemporal = null;
    /**
     * Creates new form Ventas
     */
    public Ventas(int idUsuarioQueEntro) {
        initComponents();
        this.idCajeroActivo = idUsuarioQueEntro;
        cargarTabla();
        cargarNumeroFactura();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblNumero = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxtCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBtnClientes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtCode = new javax.swing.JTextField();
        jTxtNombrePro = new javax.swing.JTextField();
        jSpnCantidad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jBtnAgregar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblDetalleVenta = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtSubtotal = new javax.swing.JTextField();
        jTxtIVA = new javax.swing.JTextField();
        jTxtTotal = new javax.swing.JTextField();
        jBtnQuitar = new javax.swing.JButton();
        jBtnGenerarVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setText("Cédula del Cliente");

        jTxtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCedulaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre del Cliente");

        jTxtNombre.setEnabled(false);

        jLabel3.setText("Si no se llena el campo de Cédula se envía como consumidor final.");

        jBtnClientes.setText("+");
        jBtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNombre))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnClientes)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel4.setText("Código del Producto");

        jLabel5.setText("Nombre del Producto");

        jTxtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodeActionPerformed(evt);
            }
        });

        jTxtNombrePro.setEnabled(false);

        jLabel6.setText("Cantidad del Producto");

        jBtnAgregar.setText("Agregar Producto");
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtCode, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(jSpnCantidad)
                    .addComponent(jTxtNombrePro))
                .addGap(18, 18, 18)
                .addComponent(jBtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTblDetalleVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblDetalleVenta);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
        );

        jLabel7.setText("Subtotal:");

        jLabel8.setText("IVA 15%:");

        jLabel9.setText("Total a pagar:");

        jTxtSubtotal.setEnabled(false);

        jTxtIVA.setEnabled(false);

        jTxtTotal.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTxtIVA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jTxtSubtotal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtTotal))
                .addGap(203, 203, 203))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jBtnQuitar.setText("Quitar Producto");
        jBtnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnQuitarActionPerformed(evt);
            }
        });

        jBtnGenerarVenta.setText("Generar Venta");
        jBtnGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGenerarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnGenerarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnQuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGenerarVenta))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodeActionPerformed
        // TODO add your handling code here:
        if (!"".equals(jTxtCode.getText())) {
            dao.ProductoDAO daoProd = new dao.ProductoDAO();
            modelo.Producto producto = daoProd.buscarPorCodigo(jTxtCode.getText());

            
        if (producto != null) {
                productoTemporal = producto; 
                jTxtNombrePro.setText(producto.getNombre());
                jSpnCantidad.setValue(1); 
                jSpnCantidad.requestFocus(); 
            }else {
                javax.swing.JOptionPane.showMessageDialog(null, "Producto no encontrado o código incorrecto");
                jTxtNombrePro.setText("");
                jTxtCode.requestFocus(); 
            }
        }
        
    }//GEN-LAST:event_jTxtCodeActionPerformed

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        // TODO add your handling code here:
        if (productoTemporal != null) {
            int cantidad = Integer.parseInt(jSpnCantidad.getValue().toString());

            if (cantidad > 0) {
                if (cantidad <= productoTemporal.getStock()) {
                    double subtotalItem = cantidad * productoTemporal.getPrecio();

                    Object[] fila = new Object[6]; 
                    fila[0] = productoTemporal.getIdProducto(); 
                    fila[1] = productoTemporal.getCodigo();
                    fila[2] = productoTemporal.getNombre();
                    fila[3] = productoTemporal.getPrecio();
                    fila[4] = cantidad;
                    fila[5] = subtotalItem;
                    tablita.addRow(fila);

                    calcularTotales();

                    jTxtCode.setText("");
                    jTxtNombrePro.setText("");
                    jSpnCantidad.setValue(0);
                    productoTemporal = null;
                    jTxtCode.requestFocus();

                } else {
                    javax.swing.JOptionPane.showMessageDialog(null, "Stock insuficiente. Stock actual: " + productoTemporal.getStock());
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "La cantidad debe ser mayor a 0");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Primero busca un producto presionando Enter en el código");
        }
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jBtnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnQuitarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jTblDetalleVenta.getSelectedRow();
        if (filaSeleccionada >= 0) {
            tablita.removeRow(filaSeleccionada);
            calcularTotales(); // Recalculamos el dinero al quitar la fila
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Selecciona un producto de la tabla para quitarlo");
        }
    }//GEN-LAST:event_jBtnQuitarActionPerformed

    private void jBtnGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGenerarVentaActionPerformed
        // TODO add your handling code here:
        if (jTblDetalleVenta.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "El carrito está vacío. Agregue productos.");
            return;
        }

        modelo.Factura factura = new modelo.Factura();
        factura.setNumeroFactura(jLblNumero.getText().replace("Factura Nro: ", "")); 
        factura.setIdCliente(idClienteFactura);
        factura.setIdUsuario(this.idCajeroActivo); 
        factura.setSubtotal(subtotalVenta);
        factura.setPorcentajeIva(15.00); 
        factura.setTotalIva(ivaVenta);
        factura.setTotal(totalVenta);

        java.util.List<modelo.DetalleFactura> lista = new java.util.ArrayList<>();

        for (int i = 0; i < jTblDetalleVenta.getRowCount(); i++) {
            modelo.DetalleFactura detalle = new modelo.DetalleFactura();

            detalle.setIdProducto(Integer.parseInt(jTblDetalleVenta.getValueAt(i, 0).toString()));
            detalle.setPrecioUnitario(Double.parseDouble(jTblDetalleVenta.getValueAt(i, 3).toString()));
            detalle.setCantidad(Integer.parseInt(jTblDetalleVenta.getValueAt(i, 4).toString()));
            detalle.setSubtotalItem(Double.parseDouble(jTblDetalleVenta.getValueAt(i, 5).toString()));

            lista.add(detalle);
        }

        dao.FacturaDAO daoFac = new dao.FacturaDAO();
        if (daoFac.registrarVenta(factura, lista)) {
            javax.swing.JOptionPane.showMessageDialog(null, "¡Venta Registrada Exitosamente!");
            try {
                java.sql.Connection con = modelo.Conexion.conectar();

                java.io.InputStream rutaReporte = getClass().getResourceAsStream("/reportes/Factura.jasper");

                java.util.Map<String, Object> parametros = new java.util.HashMap<>();
                parametros.put("NUM_FACTURA", factura.getNumeroFactura()); 

                net.sf.jasperreports.engine.JasperPrint jp = net.sf.jasperreports.engine.JasperFillManager.fillReport(rutaReporte, parametros, con);

                net.sf.jasperreports.view.JasperViewer.viewReport(jp, false);

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error al generar la factura: " + e.getMessage());
            }
        

            tablita.setRowCount(0); 
            calcularTotales(); 
            jTxtCedula.setText("");
            jTxtNombre.setText("");
            idClienteFactura = 0; 
            cargarNumeroFactura(); 
        }
    }//GEN-LAST:event_jBtnGenerarVentaActionPerformed

    private void jTxtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCedulaActionPerformed
        // TODO add your handling code here:
        String cedula = jTxtCedula.getText().trim();

        if (!cedula.isEmpty()) {
            dao.ClienteDAO daoCli = new dao.ClienteDAO();
            modelo.Cliente clienteEncontrado = daoCli.buscarPorCedula(cedula);

            if (clienteEncontrado != null) {
                jTxtNombre.setText(clienteEncontrado.getNombre());
                idClienteFactura = clienteEncontrado.getIdCliente();
                jTxtCode.requestFocus();
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Cliente no encontrado. Se facturará como Consumidor Final.");
                jTxtNombre.setText("Consumidor Final");
                idClienteFactura = 0;
                jTxtCode.requestFocus();
            }
        } else {
            jTxtNombre.setText("Consumidor Final");
            idClienteFactura = 0;
            jTxtCode.requestFocus();
        }
    }//GEN-LAST:event_jTxtCedulaActionPerformed

    private void jBtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClientesActionPerformed
        // TODO add your handling code here:
        Clientes ventanaClientes = new Clientes();
        ventanaClientes.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);

        ventanaClientes.setLocationRelativeTo(null);
        ventanaClientes.setVisible(true);
    }//GEN-LAST:event_jBtnClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void cargarTabla(){
        tablita.addColumn("ID");
        tablita.addColumn("Código");
        tablita.addColumn("Nombre");
        tablita.addColumn("Precio");
        tablita.addColumn("Cantidad");
        tablita.addColumn("Subtotal");
        jTblDetalleVenta.setModel(tablita);
    }
    
    public void calcularTotales() {
        subtotalVenta = 0.0;
        for (int i = 0; i < jTblDetalleVenta.getRowCount(); i++) {
            subtotalVenta += Double.parseDouble(jTblDetalleVenta.getValueAt(i, 5).toString()); 
        }

        ivaVenta = subtotalVenta * 0.15;
        totalVenta = subtotalVenta + ivaVenta;

        jTxtSubtotal.setText(String.format("%.2f", subtotalVenta));
        jTxtIVA.setText(String.format("%.2f", ivaVenta));
        jTxtTotal.setText(String.format("%.2f", totalVenta));
    }
    
    public void cargarNumeroFactura() {
        dao.FacturaDAO daoFac = new dao.FacturaDAO();
        String num = daoFac.generarNumeroFactura();
        jLblNumero.setText("Factura Nro: " + num);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnClientes;
    private javax.swing.JButton jBtnGenerarVenta;
    private javax.swing.JButton jBtnQuitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblNumero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpnCantidad;
    private javax.swing.JTable jTblDetalleVenta;
    private javax.swing.JTextField jTxtCedula;
    private javax.swing.JTextField jTxtCode;
    private javax.swing.JTextField jTxtIVA;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtNombrePro;
    private javax.swing.JTextField jTxtSubtotal;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
}
